=== BrandonMFong/Roloflex/Schema/Roloflex.xsd
<?xml version = "1.0" encoding = "UTF-8"?>
<xs:schema xmlns:xs = "http://www.w3.org/2001/XMLSchema">
   <!-- FTP -->
   <xs:element name="Site">
        <xs:element name="Environment"/>

        <!-- FTP -->
        <xs:element name="Destination">
            <xs:attribute name="Name"/>
            <xs:element name="Site"/>
            <xs:element name="Processes">
                <xs:element name="Process">
                    <xs:element name="Tag"/>
                    <xs:element name="LCD"/>
                    <xs:element name="CD"/>
                    <xs:element name="Package"/>
                </xs:element>
            </xs:element>
        </xs:element>
        
        <!-- Environment Credentials -->
        <xs:element name="Variables">
            <xs:element name="Variable">
                <xs:attribute name="Environment"/>
                <xs:element name="Servername"/>
                <xs:element name="Username"/>
                <xs:element name="Password"/>
                <xs:element name="Database"/>
            </xs:element>
        </xs:element>
    </xs:element>
</xs:schema>

=== BrandonMFong/Roloflex/config/Transfer.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<Site 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="..\schema\Roloflex.xsd">
    <Destination Name="Default">
        <Site>kojami</Site>
        <Processes><!-- Not specifying if it is put or get -->
            <Process>
                <Tag>Configuration Files : Application.xml</Tag>
                <LCD>B:\SOURCES\Repos\Roloflex\config</LCD>
                <CD>/var/www/site/Roloflex/config</CD>
                <Package>Application.xml</Package>
            </Process>
            <Process>
                <Tag>Configuration File : Env.xml</Tag>
                <LCD>B:\SOURCES\Repos\Roloflex\config</LCD>
                <CD>/var/www/site/Roloflex/config</CD>
                <Package>Env.xml</Package>
            </Process>
            <Process>
                <Tag>import files</Tag>
                <LCD>B:\SOURCES\Repos\Roloflex</LCD>
                <CD>/var/www/site/Roloflex</CD>
                <Package>imports</Package>
            </Process>
        </Processes>
    </Destination>
</Site>
